name: Dependabot auto-merge
on: 
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'MasatoMakino/release-helper'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.dependency-type == 'direct:development' && steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr comment "$PR_NUMBER" --body "@dependabot squash and merge"
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}